"""
File: save_outputs.py
Author: Nayma Nur
Description: This script is dedicated to saving all outputs generated by the models into CSV files.
             It handles the exporting of statistical summaries and other data into structured CSV
             format, organizing the files in designated directories as per project requirements.
"""




import numpy as np



def write_statistics_to_file(mu_nrmse, median_nrmse, min_nrmse, sigma_nrmse, mu_r2, median_r2, max_r2, sigma_r2, model_output):
    """
    Writes statistical summaries to a CSV file.

    Args:
        mu_nrmse (float): Mean of normalized root mean square error.
        median_nrmse (float): Median of normalized root mean square error.
        min_nrmse (float): Minimum of normalized root mean square error.
        sigma_nrmse (float): Standard deviation of normalized root mean square error.
        mu_r2 (float): Mean of R-squared values.
        median_r2 (float): Median of R-squared values.
        max_r2 (float): Maximum of R-squared values.
        sigma_r2 (float): Standard deviation of R-squared values.
        model_output (str): Path to the directory where the output CSV file will be saved.

    Notes:
        The function creates a file named 'bootstrap_model_statistics.csv' in the specified directory
        and writes the provided statistical data into it. If the directory does not exist, it is created.
    """



    # Write to file
    with open(model_output + 'bootstrap_model_statistics.csv', 'w') as f:

        f.write('Test Data Statistics:\n')
        f.write('\n')

        f.write('Mean r2-val = ' + str(np.round(mu_r2, 3)) + '\n')
        f.write('Median r2-val = ' + str(np.round(median_r2, 3)) + '\n')
        f.write('Max r2-val = ' + str(np.round(max_r2, 3)) + '\n')
        f.write('St dev. r2-val = ' + str(np.round(sigma_r2, 3)) + '\n')
        f.write('\n')

        f.write('Mean nrmse = ' + str(np.round(mu_nrmse, 3)) + '\n')
        f.write('Median nrmse = ' + str(np.round(median_nrmse, 3)) + '\n')
        f.write('Min nrmse = ' + str(np.round(min_nrmse, 3)) + '\n')
        f.write('St dev. nrmse = ' + str(np.round(sigma_nrmse, 3)) + '\n')
        f.write('\n')



